// Single source of truth. Add a project here and it appears on the homepage,
// gets its own /work/[slug] page, and is picked up by the sitemap.
// Nothing else needs editing.

export type Spec = { key: string; value: string };

export type Project = {
  slug: string;
  title: string;
  summary: string;
  /** Homepage paragraphs. Keep to three. Depth goes on the detail page. */
  body: string[];
  specs: Spec[];
  liveUrl?: string;
  repoUrl?: string;
  /** Shown instead of a repo link when the source can't be public. */
  privateNote?: string;
  /** Longer-form sections rendered only on /work/[slug]. */
  detail?: { heading: string; paragraphs: string[] }[];
};

export const projects: Project[] = [
  {
    slug: "mamichie-healthcare",
    title: "Mamichie Healthcare",
    summary:
      "E-commerce and membership platform for a UK health brand. Live, taking payments, still shipping.",
    body: [
      "A rebuild with a launch date attached. First commit on 9 June; Stripe subscriptions were taking real payments on 20 June. Eleven days from empty repository to revenue.",
      "What went in during that window: tiered memberships billed as Stripe subscriptions, a member dashboard on Supabase, transactional confirmations through Resend, Calendly and Zoom for consultation booking, and a clinical article library rendered from markdown with proper table support. British English throughout — the brand is UK, and American spellings were the first thing the client caught.",
      "The bug that cost a day was environment variables. The Supabase client worked locally and failed in production with credentials that looked byte-identical in both places. They weren't: the values carried trailing whitespace, and Vercel's build cache was serving stale copies on top of that. Now I validate and trim env values at startup rather than trusting that what I pasted is what arrives.",
    ],
    specs: [
      { key: "PERIOD", value: "June 2026 — present" },
      { key: "TO FIRST PAYMENT", value: "11 days" },
      { key: "STACK", value: "Next.js, Supabase, Stripe, Resend" },
      { key: "ROLE", value: "Sole developer" },
    ],
    liveUrl: "https://mamichiehealthcare.com",
    privateNote: "Private repository, client work",
    detail: [
      {
        heading: "Payments",
        paragraphs: [
          "Memberships are recurring rather than one-off, which means the interesting states are the ones after checkout: renewal, failure, downgrade, cancellation. Stripe owns billing truth; the application reconciles against it rather than duplicating it, so a webhook that arrives late produces a delay, not a wrong entitlement.",
        ],
      },
      {
        heading: "Content pipeline",
        paragraphs: [
          "The clinical library is markdown with remark-gfm, so the client writes articles containing real tables without touching a CMS or a component. Thumbnails resolve through an image map, which keeps article files portable.",
        ],
      },
      {
        heading: "Working with a non-technical client",
        paragraphs: [
          "Roughly a fifth of the commit history is content edits made directly through GitHub's web interface. That was a deliberate trade: the client can fix a typo at midnight without me, at the cost of a messier history and the occasional merge to resolve. For a two-person project that was the right call.",
        ],
      },
    ],
  },
  {
    slug: "jamloyalty",
    title: "JamLoyalty",
    summary:
      "White-label digital loyalty platform for Caribbean merchants. Merchant dashboard, staff scanner, customer wallet.",
    body: [
      "Paper punch cards cost money to print, get lost, and tell the business nothing. JamLoyalty replaces them with three connected surfaces: a merchant dashboard for building campaigns and branding, a staff terminal that scans, and a customer wallet that saves to the phone's home screen and tracks stamps live over database subscriptions.",
      "The problem worth solving was fraud. A loyalty stamp has cash value, so a static QR code is an open invitation — photograph it once and self-stamp forever. Codes are signed with HMAC-SHA256, rotate every fifteen seconds, and are checked server-side against replay, so a screenshot is worthless almost immediately. Staff reach the scanner through a per-location code issued from the merchant dashboard, so a leaked link doesn't become a leaked till.",
      "Customers sign in by phone OTP through Twilio rather than email, because email isn't the default identity in this market. Passes can be added to Google Wallet, generated by a serverless function. Each merchant carries their own branding and is isolated from every other merchant by Postgres row-level security.",
    ],
    specs: [
      { key: "PERIOD", value: "Jan — Mar 2026" },
      { key: "USERS", value: "Merchant, staff, customer" },
      { key: "STACK", value: "React, Supabase, Firebase, Twilio" },
      { key: "NOTABLE", value: "HMAC-SHA256 rotating QR, anti-replay" },
    ],
    liveUrl: "https://jam-loyalty.vercel.app",
    detail: [
      {
        heading: "Why rotating codes",
        paragraphs: [
          "The threat isn't a sophisticated attacker, it's an ordinary customer with a screenshot and a staff member who isn't watching closely. A signed, short-lived code makes both attacks expire faster than they can be executed, without asking staff to do anything differently.",
        ],
      },
      {
        heading: "Multi-tenancy",
        paragraphs: [
          "Merchant isolation is enforced in Postgres through row-level security rather than in application queries. A missing WHERE clause in a React component cannot leak one business's customer list to another, because the database refuses the rows regardless of what the query asks for.",
        ],
      },
    ],
  },
  {
    slug: "muchemi-law-portal",
    title: "Muchemi Law Portal",
    summary:
      "Practice management system for a law firm. Paired web and Android clients.",
    body: [
      "Legal case files are the kind of data where a permissions bug is a professional liability, not a bug report. Access control lives in Postgres row-level security rather than in application code, so a mistake in a React component cannot expose another member's matters.",
      "Two pieces removed real manual work. Scheduled jobs fire a staged reminder cascade three days, one day and one hour before every court date and deadline. A docket generator compiles current database state into a print-ready PDF on demand, replacing a copy-and-paste ritual that used to happen before every hearing.",
    ],
    specs: [
      { key: "PERIOD", value: "Jan — Feb 2026" },
      { key: "CLIENT", value: "County Attorney, Laikipia" },
      { key: "STACK", value: "Next.js 14, Supabase, cron, Resend" },
      { key: "NOTABLE", value: "RLS access control, staged alerts" },
    ],
    privateNote: "Private, confidential client data",
  },
  {
    slug: "kinap-lab-inventory",
    title: "KINAP Lab Inventory",
    summary:
      "Offline-first inventory and point of sale for the mechatronics laboratory I run.",
    body: [
      "The lab tracked components and consumables on paper, which meant nobody knew what was in stock until they went looking for something and didn't find it. I built the replacement, and I'm also the person who uses it every week — the fastest feedback loop I've had on anything I've written.",
      "Campus connectivity drops constantly, so the app writes locally first and reconciles on reconnect rather than blocking on the network. Students check equipment in and out by QR scan.",
    ],
    specs: [
      { key: "PERIOD", value: "Feb — Mar 2026" },
      { key: "USERS", value: "Mechatronics dept., KIST" },
      { key: "STACK", value: "Flutter, Supabase" },
      { key: "NOTABLE", value: "Offline write, reconcile on reconnect" },
    ],
    repoUrl: "https://github.com/waruikiondo/kist-admin-portal",
  },
];

export type ArchiveRow = {
  year: string;
  name: string;
  what: string;
  stack: string;
  href?: string;
  hrefLabel?: string;
};

export const archive: ArchiveRow[] = [
  { year: "2025–26", name: "Proudly Laikipian", what: "Editorial and booking site for a tourism brand", stack: "Next.js, Sanity, Cloudinary", href: "https://proudly-laikipian-site.vercel.app", hrefLabel: "Live" },
  { year: "2026", name: "SNC Horizon", what: "Network topology digital twin, live telemetry", stack: "Flutter CanvasKit", href: "https://github.com/waruikiondo/snc-client-suite", hrefLabel: "Source" },
  { year: "2026", name: "Cklist", what: "Workflow app with end-to-end type safety", stack: "tRPC, Prisma, NextAuth, Zod", href: "https://cklist-jamaica.vercel.app", hrefLabel: "Live" },
  { year: "2026", name: "Gamify", what: "Learning app with exam-paper parser", stack: "Flutter, Supabase", href: "https://github.com/waruikiondo/gamify-app", hrefLabel: "Source" },
  { year: "2026", name: "Lishe Yetu", what: "Nutrition guidance with conversational assistant", stack: "Next.js, Supabase", href: "https://lishe-yetu-site.vercel.app", hrefLabel: "Live" },
  { year: "2026", name: "Axis Home Healthcare", what: "Care provider site and enquiry flow", stack: "Next.js, Framer Motion", href: "https://axis-home-healthcare.vercel.app", hrefLabel: "Live" },
  { year: "2023–", name: "Brachel Jones Realty", what: "Rebuild with Georgia MLS feed integration", stack: "React, MLS API" },
  { year: "2026", name: "EngArch", what: "Engineering consultancy site", stack: "Next.js", href: "https://engarch-website-seven.vercel.app", hrefLabel: "Live" },
];

export const octocopterPlates = [
  { src: "/octocopter/assembly-01.png", alt: "Acrylic hub and machined aluminium arms during assembly", caption: "AIRFRAME ASSEMBLY" },
  { src: "/octocopter/flight-controller-pcb-layout.png", alt: "KiCad layout of the flight controller board", caption: "FLIGHT CONTROLLER, KICAD" },
  { src: "/octocopter/simulink-6dof-model.png", alt: "Simulink six-degree-of-freedom model", caption: "6-DOF MODEL, SIMULINK" },
  { src: "/octocopter/z-position-tracking.png", alt: "Altitude tracking response from simulation", caption: "ALTITUDE TRACKING" },
];
